"""
baselines_real.py

Benchmark models for post-Ian communities using the same data
generated by `prepare_real_ian_by_cbg.py`.

Baselines implemented (prediction-only):
  1. Cox / survival (time to first sell / repair)
  2. RUM / logistic panel model
  3. Spatial lag / Durbin-style logistic panel
  4. RecovUS-style ABM-ish logistic (community functionality)
  5. Neural RNN / RMTPP-style discrete-time sequence model

All baselines operate on the same NPZ as your Graph Hawkes model:
  - communities: list of dicts with keys 'X', 'Y', 'coords', 'node_ids'
  - meta: dict with 'T', 'T_train', 'T_val', etc.
"""

from __future__ import annotations
from typing import List, Dict, Tuple
from typing_extensions import Literal

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

# Optional for Cox baseline
try:
    import pandas as pd
    from lifelines import CoxPHFitter
    HAS_LIFELINES = True
except ImportError:
    HAS_LIFELINES = False

# We reuse your utilities where useful
from train_eval_multi_real import (
    select_communities_by_distance,
    evaluate_tail_metrics,
)


# ----------------------------------------------------------------------
# Helpers: load data and build simple spatial networks
# ----------------------------------------------------------------------

def load_real_communities(
    npz_path: str,
    ref_lon: float,
    ref_lat: float,
    max_communities: int,
    min_nodes_real: int,
    max_nodes_real: int,
) -> Tuple[List[dict], Dict, List[int]]:
    """
    Load NPZ from prepare_real_ian_by_cbg.py and select a subset of communities
    using the same selection heuristic as your Graph Hawkes pipeline.

    Returns:
        communities: list of dicts
        meta: meta dict
        selected_indices: indices into the original communities array
    """
    data = np.load(npz_path, allow_pickle=True)
    communities_all = list(data["communities"])
    meta = data["meta"].item()

    selected_indices = select_communities_by_distance(
        communities=communities_all,
        ref_lon=ref_lon,
        ref_lat=ref_lat,
        max_communities=max_communities,
        min_nodes=min_nodes_real,
        max_nodes=max_nodes_real,
    )
    communities = [communities_all[i] for i in selected_indices]
    return communities, meta, selected_indices


def build_knn_weights(coords: np.ndarray, k: int = 5) -> np.ndarray:
    """
    Construct a simple kNN spatial weights matrix W [N, N] from coordinates.

    coords: [N, 2] with (lat, lon) or (lon, lat) consistently.
    W_ij = 1/k if j is among i's k nearest neighbors, else 0.
    Rows normalized to sum to 1 (typical spatial lag construction).

    This is commonly used in spatial econometrics and diffusion models.
    """
    N = coords.shape[0]
    # Use Euclidean distance in (lat, lon) for simplicity
    dists = np.sum((coords[:, None, :] - coords[None, :, :]) ** 2, axis=2)  # [N, N]
    np.fill_diagonal(dists, np.inf)

    # indices of k nearest neighbors per i
    knn_idx = np.argpartition(dists, kth=k, axis=1)[:, :k]  # [N, k]

    W = np.zeros((N, N), dtype=np.float32)
    for i in range(N):
        neighbors = knn_idx[i]
        W[i, neighbors] = 1.0 / float(k)

    return W


# ----------------------------------------------------------------------
# Generic panel builder for (t, node) -> features and labels
# ----------------------------------------------------------------------

def build_panel_data(
    communities: List[dict],
    meta: Dict,
    mode: Literal["rum", "spatial_lag", "recovus"],
    k_neighbors: int = 5,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, List[Tuple[int, int]]]:
    """
    Build panel data for discrete-time logistic baselines.

    We construct samples of the form:
        X_panel[n, :]  - features for one (t, i) pair
        Y_panel[n, k]  - binary label for sell/repair at time t
        time_idx[n]    - time index t (0-based)
        index_map[n]   - (g, i) -> community index and node index

    For training, you will typically restrict to t < T_train.
    For prediction, you rebuild features for all t and use fitted model.

    mode:
      - "rum": random utility / logit with:
            [X_i, t/T, t^2/T^2]
      - "spatial_lag": plus spatial lag of last-period events via kNN W
      - "recovus": plus community functionality indices
            (share_repaired, share_sold in the community at t-1)
    """
    T = int(meta["T"])
    T_train = int(meta["T_train"])
    K = 2  # sell, repair

    X_list = []
    Y_list = []
    t_list = []
    idx_list = []

    for g, comm in enumerate(communities):
        X_g = comm["X"].astype(np.float32)  # [N_g, d]
        Y_g = comm["Y"].astype(np.float32)  # [T, N_g, K]
        coords_g = comm["coords"].astype(np.float32)  # [N_g, 2]
        T_g, N_g, _ = Y_g.shape
        assert T_g == T, "Inconsistent T across communities"

        # Precompute W_g if needed
        W_g = None
        if mode == "spatial_lag":
            W_g = build_knn_weights(coords_g, k=k_neighbors)

        for t in range(1, T_train):  # use t>=1 so we can look at t-1
            # Current-period labels (exact events)
            Y_t = Y_g[t]  # [N_g, K]
            # Last-period events
            Y_prev = Y_g[t - 1]  # [N_g, K]

            # Time features (normalized)
            t_norm = t / float(T)
            time_feats = np.array([t_norm, t_norm ** 2], dtype=np.float32)

            # Community-level functionality (for RecovUS mode)
            if mode == "recovus":
                # Fraction repaired & sold at t-1 in this CBG
                frac_sold_prev = float(Y_prev[:, 0].sum()) / max(N_g, 1)
                frac_rep_prev = float(Y_prev[:, 1].sum()) / max(N_g, 1)
                comm_feats = np.array(
                    [frac_sold_prev, frac_rep_prev, 1.0 - frac_sold_prev],
                    dtype=np.float32,
                )  # last term ~ "remaining occupancy"
            else:
                comm_feats = np.zeros(0, dtype=np.float32)

            # Spatial lags (for spatial_lag mode)
            if mode == "spatial_lag":
                # spatial lag of last-period sell/repair
                lag_sell = W_g @ Y_prev[:, 0]  # [N_g]
                lag_rep = W_g @ Y_prev[:, 1]   # [N_g]
                spatial_feats = np.stack([lag_sell, lag_rep], axis=1)  # [N_g, 2]
            else:
                spatial_feats = None

            for i in range(N_g):
                base = X_g[i]  # [d]
                feats = [base, time_feats]

                if mode == "recovus":
                    feats.append(comm_feats)
                if mode == "spatial_lag":
                    feats.append(spatial_feats[i])

                x_i = np.concatenate(feats, axis=0)  # 1D feature vector

                X_list.append(x_i)
                Y_list.append(Y_t[i])  # [K]
                t_list.append(t)
                idx_list.append((g, i))

    X_panel = np.stack(X_list, axis=0).astype(np.float32)  # [N_samples, d']
    Y_panel = np.stack(Y_list, axis=0).astype(np.float32)  # [N_samples, K]
    t_panel = np.array(t_list, dtype=np.int64)
    idx_map = idx_list  # list of (g, i)

    return X_panel, Y_panel, t_panel, idx_map


# ----------------------------------------------------------------------
# Simple multi-label logistic model (for RUM, spatial lag, RecovUS)
# ----------------------------------------------------------------------

class PanelLogitBaseline(nn.Module):
    def __init__(self, d_in: int, K: int = 2, hidden_dim: int = 0):
        super().__init__()
        if hidden_dim > 0:
            self.net = nn.Sequential(
                nn.Linear(d_in, hidden_dim),
                nn.ReLU(),
                nn.Linear(hidden_dim, K),
            )
        else:
            self.net = nn.Linear(d_in, K)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x: [N, d_in]
        return self.net(x)  # [N, K]


def train_panel_logit(
    X_train: np.ndarray,
    Y_train: np.ndarray,
    num_epochs: int = 20,
    lr: float = 1e-3,
    hidden_dim: int = 0,
    device: str = "cpu",
) -> PanelLogitBaseline:
    """
    Train a simple multi-label logistic model with BCEWithLogitsLoss.
    """
    K = Y_train.shape[1]
    d_in = X_train.shape[1]

    X_t = torch.from_numpy(X_train).to(device)
    Y_t = torch.from_numpy(Y_train).to(device)

    # imbalance-aware pos_weight
    flat = Y_train.reshape(-1, K)
    pos = flat.sum(axis=0).astype(float)
    neg = flat.shape[0] - pos
    pos[pos <= 0.0] = 1.0
    neg[neg <= 0.0] = 1.0
    ratio = neg / pos
    pos_weight = torch.from_numpy(np.sqrt(ratio)).float().to(device)

    model = PanelLogitBaseline(d_in=d_in, K=K, hidden_dim=hidden_dim).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)

    for epoch in range(1, num_epochs + 1):
        model.train()
        optimizer.zero_grad()
        logits = model(X_t)
        loss = loss_fn(logits, Y_t)
        loss.backward()
        optimizer.step()

        if epoch == 1 or epoch % 5 == 0 or epoch == num_epochs:
            print(f"[PanelLogit epoch {epoch:03d}] loss={loss.item():.4f}")

    return model


def predict_panel_logit_logits(
    model: PanelLogitBaseline,
    communities: List[dict],
    meta: Dict,
    mode: Literal["rum", "spatial_lag", "recovus"],
    k_neighbors: int = 5,
    device: str = "cpu",
) -> Dict[int, np.ndarray]:
    """
    Use a trained PanelLogitBaseline to produce logits_dict[g]:
        logits[g]: [T, N_g, K] for exact events.
    We rebuild the same type of features but over the full horizon 1..T-1,
    and set logits[0] = 0.
    """
    model.eval()
    T = int(meta["T"])
    K = 2
    logits_dict: Dict[int, np.ndarray] = {}

    with torch.no_grad():
        for g, comm in enumerate(communities):
            X_g = comm["X"].astype(np.float32)  # [N_g, d0]
            Y_g = comm["Y"].astype(np.float32)  # [T, N_g, K]
            coords_g = comm["coords"].astype(np.float32)
            T_g, N_g, _ = Y_g.shape
            assert T_g == T

            # Precompute W_g if needed
            W_g = None
            if mode == "spatial_lag":
                W_g = build_knn_weights(coords_g, k=k_neighbors)

            logits_g = np.zeros((T, N_g, K), dtype=np.float32)

            for t in range(1, T):
                Y_prev = Y_g[t - 1]
                t_norm = t / float(T)
                time_feats = np.array([t_norm, t_norm ** 2], dtype=np.float32)

                if mode == "recovus":
                    frac_sold_prev = float(Y_prev[:, 0].sum()) / max(N_g, 1)
                    frac_rep_prev = float(Y_prev[:, 1].sum()) / max(N_g, 1)
                    comm_feats = np.array(
                        [frac_sold_prev, frac_rep_prev, 1.0 - frac_sold_prev],
                        dtype=np.float32,
                    )
                else:
                    comm_feats = np.zeros(0, dtype=np.float32)

                if mode == "spatial_lag":
                    lag_sell = W_g @ Y_prev[:, 0]
                    lag_rep = W_g @ Y_prev[:, 1]
                    spatial_feats = np.stack([lag_sell, lag_rep], axis=1)
                else:
                    spatial_feats = None

                X_list = []
                for i in range(N_g):
                    base = X_g[i]
                    feats = [base, time_feats]
                    if mode == "recovus":
                        feats.append(comm_feats)
                    if mode == "spatial_lag":
                        feats.append(spatial_feats[i])
                    X_list.append(np.concatenate(feats, axis=0))

                X_t = np.stack(X_list, axis=0).astype(np.float32)  # [N_g, d_in]
                X_t_torch = torch.from_numpy(X_t).to(device)
                logits_t = model(X_t_torch).cpu().numpy()  # [N_g, K]
                logits_g[t] = logits_t

            logits_dict[g] = logits_g

    return logits_dict


# ----------------------------------------------------------------------
# Cox / survival baseline (time to first sell / repair)
# ----------------------------------------------------------------------

def build_cox_dataset(communities: List[dict], meta: Dict, event_type: int):
    """
    Build dataset for a Cox model: one row per node, with
      - duration: time to first event of `event_type` (0 or 1)
      - event: 1 if event observed, 0 if censored
      - covariates: static X_i

    event_type: 0 = sell, 1 = repair
    """
    T = int(meta["T"])
    X_rows = []
    durations = []
    events = []

    for comm in communities:
        X_g = comm["X"].astype(np.float32)    # [N_g, d]
        Y_g = comm["Y"].astype(np.float32)    # [T, N_g, K]
        T_g, N_g, _ = Y_g.shape
        assert T_g == T

        for i in range(N_g):
            y_i = Y_g[:, i, event_type]  # [T]
            if y_i.sum() > 0:
                t_event = int(np.argmax(y_i > 0))  # first month index
                event = 1
            else:
                t_event = T - 1
                event = 0

            durations.append(t_event + 1)  # months since start, 1-based
            events.append(event)
            X_rows.append(X_g[i])

    X_mat = np.stack(X_rows, axis=0)
    durations = np.array(durations, dtype=np.float32)
    events = np.array(events, dtype=np.int32)
    return X_mat, durations, events


def train_cox(
    communities: List[dict],
    meta: Dict,
    event_type: int,
    feature_names: List[str] | None = None,
):
    """
    Fit a CoxPH model for sell (event_type=0) or repair (event_type=1)
    using lifelines. This is a node-level time-to-first-event model.

    Returns the fitted CoxPHFitter. You can use it to get survival and
    hazard estimates and then translate them into per-(t,i) probabilities.
    """
    if not HAS_LIFELINES:
        raise RuntimeError("lifelines is not installed; install via `pip install lifelines`.")

    X_mat, durations, events = build_cox_dataset(communities, meta, event_type)
    N, d = X_mat.shape

    if feature_names is None:
        feature_names = [f"x{j}" for j in range(d)]

    df = pd.DataFrame(X_mat, columns=feature_names)
    df["duration"] = durations
    df["event"] = events

    cph = CoxPHFitter()
    cph.fit(df, duration_col="duration", event_col="event", show_progress=True)
    return cph


def cox_predict_logits_per_t(
    cph_sell,
    cph_rep,
    communities: List[dict],
    meta: Dict,
    feature_names: List[str],
) -> Dict[int, np.ndarray]:
    """
    Example: translate CoxPH predictions into per-(t,i,k) logits.

    For each node i, and each time t, we compute approximate probability
    that event happens at t (given it has not happened yet):
        p(t) ≈ S(t-1) - S(t)
    where S(t) is survival probability from CoxPH.

    This produces a logits_dict[g] with shape [T, N_g, 2].
    """
    T = int(meta["T"])
    logits_dict: Dict[int, np.ndarray] = {}

    for g, comm in enumerate(communities):
        X_g = comm["X"].astype(np.float32)
        Y_g = comm["Y"].astype(np.float32)
        T_g, N_g, K = Y_g.shape
        assert T_g == T

        df_X = pd.DataFrame(X_g, columns=feature_names)

        # times 1..T as months
        times = np.arange(1, T + 1)

        # Survival for each node and type
        S_sell = cph_sell.predict_survival_function(df_X, times=times)  # DataFrame: index=times, columns=nodes
        S_rep = cph_rep.predict_survival_function(df_X, times=times)

        logits_g = np.zeros((T, N_g, 2), dtype=np.float32)

        for i in range(N_g):
            # series indexed by time
            S_s_i = S_sell.iloc[:, i].values  # length T
            S_r_i = S_rep.iloc[:, i].values

            for t in range(T):
                S_prev_s = 1.0 if t == 0 else S_s_i[t - 1]
                S_curr_s = S_s_i[t]
                p_s = max(S_prev_s - S_curr_s, 1e-8)

                S_prev_r = 1.0 if t == 0 else S_r_i[t - 1]
                S_curr_r = S_r_i[t]
                p_r = max(S_prev_r - S_curr_r, 1e-8)

                # Convert to logits
                logits_g[t, i, 0] = np.log(p_s) - np.log(1.0 - p_s)
                logits_g[t, i, 1] = np.log(p_r) - np.log(1.0 - p_r)

        logits_dict[g] = logits_g

    return logits_dict


# ----------------------------------------------------------------------
# Neural RNN / RMTPP-style baseline (per-node GRU)
# ----------------------------------------------------------------------

class NodeSequenceRNN(nn.Module):
    """
    Simple per-node GRU baseline.

    For each node i:
      input sequence: [T-1, d_in] where d_in = K + d_static
        (past events Y[t-1, i, :] and static features X_i)
      target: Y[t, i, :] for t=1..T_train-1

    This ignores explicit network structure but captures rich
    temporal nonlinearities similar in spirit to RMTPP / Neural Hawkes.
    """

    def __init__(self, d_in: int, hidden_dim: int = 32, K: int = 2):
        super().__init__()
        self.gru = nn.GRU(input_size=d_in, hidden_size=hidden_dim, batch_first=True)
        self.out = nn.Linear(hidden_dim, K)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        x: [B, T-1, d_in]
        returns logits: [B, T-1, K]
        """
        h, _ = self.gru(x)  # [B, T-1, hidden_dim]
        logits = self.out(h)  # [B, T-1, K]
        return logits


def build_rnn_sequences(
    communities: List[dict],
    meta: Dict,
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Build sequences for NodeSequenceRNN.

    Returns:
      X_seq: [B, T-1, d_in]
      Y_seq: [B, T-1, K] (targets)
    where B = total number of nodes across selected communities.
    """
    T = int(meta["T"])
    T_train = int(meta["T_train"])
    K = 2

    X_seq_list = []
    Y_seq_list = []

    for comm in communities:
        X_g = comm["X"].astype(np.float32)    # [N_g, d_static]
        Y_g = comm["Y"].astype(np.float32)    # [T, N_g, K]
        T_g, N_g, _ = Y_g.shape
        assert T_g == T
        d_static = X_g.shape[1]

        # For training, we only use up to T_train
        for i in range(N_g):
            x_i = X_g[i]  # [d_static]
            # inputs: concatenate static X_i to each time step of past events
            past_events = Y_g[:T_train - 1, i, :]  # [T_train-1, K]
            x_rep = np.repeat(x_i[None, :], repeats=past_events.shape[0], axis=0)  # [T_train-1, d_static]
            X_i_seq = np.concatenate([past_events, x_rep], axis=1)  # [T_train-1, K + d_static]

            # targets: next events
            Y_i_seq = Y_g[1:T_train, i, :]  # [T_train-1, K]

            X_seq_list.append(X_i_seq)
            Y_seq_list.append(Y_i_seq)

    X_seq = np.stack(X_seq_list, axis=0)  # [B, T_train-1, d_in]
    Y_seq = np.stack(Y_seq_list, axis=0)  # [B, T_train-1, K]
    return X_seq, Y_seq


def train_rnn_baseline(
    communities: List[dict],
    meta: Dict,
    hidden_dim: int = 32,
    num_epochs: int = 20,
    lr: float = 1e-3,
    device: str = "cpu",
) -> NodeSequenceRNN:
    """
    Train NodeSequenceRNN baseline over all nodes in selected communities.
    """
    T = int(meta["T"])
    T_train = int(meta["T_train"])
    K = 2

    X_seq, Y_seq = build_rnn_sequences(communities, meta)
    B, Tm1, d_in = X_seq.shape

    X_t = torch.from_numpy(X_seq).to(device)
    Y_t = torch.from_numpy(Y_seq).to(device)

    model = NodeSequenceRNN(d_in=d_in, hidden_dim=hidden_dim, K=K).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    loss_fn = nn.BCEWithLogitsLoss()

    for epoch in range(1, num_epochs + 1):
        model.train()
        optimizer.zero_grad()
        logits = model(X_t)  # [B, T_train-1, K]
        loss = loss_fn(logits, Y_t)
        loss.backward()
        optimizer.step()

        if epoch == 1 or epoch % 5 == 0 or epoch == num_epochs:
            print(f"[RNN baseline epoch {epoch:03d}] loss={loss.item():.4f}")

    return model


def rnn_predict_logits_per_community(
    model: NodeSequenceRNN,
    communities: List[dict],
    meta: Dict,
    device: str = "cpu",
) -> Dict[int, np.ndarray]:
    """
    Use a trained NodeSequenceRNN to predict logits[g]: [T, N_g, K].
    We feed the full past events sequence for each node and get logits
    for t=1..T-1; we leave t=0 as zeros.
    """
    model.eval()
    T = int(meta["T"])
    K = 2
    logits_dict: Dict[int, np.ndarray] = {}

    with torch.no_grad():
        for g, comm in enumerate(communities):
            X_g = comm["X"].astype(np.float32)    # [N_g, d_static]
            Y_g = comm["Y"].astype(np.float32)    # [T, N_g, K]
            T_g, N_g, _ = Y_g.shape
            assert T_g == T
            d_static = X_g.shape[1]

            logits_g = np.zeros((T, N_g, K), dtype=np.float32)

            for i in range(N_g):
                x_i = X_g[i]
                past_events = Y_g[:-1, i, :]  # [T-1, K]
                x_rep = np.repeat(x_i[None, :], repeats=past_events.shape[0], axis=0)
                X_i_seq = np.concatenate([past_events, x_rep], axis=1)  # [T-1, K + d_static]

                X_i_torch = torch.from_numpy(X_i_seq[None, ...]).to(device)  # [1, T-1, d_in]
                logits_i = model(X_i_torch).cpu().numpy()[0]  # [T-1, K]

                logits_g[1:, i, :] = logits_i

            logits_dict[g] = logits_g

    return logits_dict


# ----------------------------------------------------------------------
# Example glue: run baselines and evaluate with your existing metrics
# ----------------------------------------------------------------------

def run_and_eval_panel_baseline(
    npz_path: str,
    baseline: Literal["rum", "spatial_lag", "recovus"],
    ref_lon: float,
    ref_lat: float,
    max_communities: int,
    min_nodes_real: int,
    max_nodes_real: int,
    num_epochs: int = 20,
    lr: float = 1e-3,
    hidden_dim: int = 0,
    device: str = "cpu",
    horizon_months: int = 6,
):
    """
    Convenience function:
      - load communities
      - build panel data
      - train panel logistic baseline
      - predict logits[g] over full horizon
      - call your existing evaluate_tail_metrics
    """
    communities, meta, _ = load_real_communities(
        npz_path, ref_lon, ref_lat, max_communities, min_nodes_real, max_nodes_real
    )
    T_train = int(meta["T_train"])

    print(f"[INFO] Loaded {len(communities)} communities from {npz_path}")
    print(f"[INFO] Training panel-{baseline} baseline...")

    X_panel, Y_panel, _, _ = build_panel_data(
        communities, meta, mode=baseline, k_neighbors=5
    )

    model = train_panel_logit(
        X_panel, Y_panel, num_epochs=num_epochs, lr=lr, hidden_dim=hidden_dim, device=device
    )

    logits_dict = predict_panel_logit_logits(
        model, communities, meta, mode=baseline, k_neighbors=5, device=device
    )

    # For simplicity, use same logits for window predictions
    window_logits_dict = logits_dict

    metrics = evaluate_tail_metrics(
        communities=communities,
        logits_dict=logits_dict,
        window_logits_dict=window_logits_dict,
        T_train=T_train,
        horizon=horizon_months,
    )
    return metrics


if __name__ == "__main__":
    # Example usage (adapt paths and parameters):
    #
    # python baselines_real.py
    #
    npz_path = "lee_ian_by_cbg_dr0.005_tr0.8.npz"
    ref_lon, ref_lat = -81.8723, 26.6406

    metrics_rum = run_and_eval_panel_baseline(
        npz_path=npz_path,
        baseline="rum",
        ref_lon=ref_lon,
        ref_lat=ref_lat,
        max_communities=200,
        min_nodes_real=100,
        max_nodes_real=900,
        num_epochs=20,
        lr=1e-3,
        hidden_dim=32,
        device="cuda" if torch.cuda.is_available() else "cpu",
        horizon_months=6,
    )
    print("\n[RUM baseline metrics]")
    for k, v in metrics_rum.items():
        print(k, ":", v)
